version: '3.8'

services:

    jni_express_template:
        container_name: jni_express_template
        image: jni_express_template
        ports:
            - "8090:8090"
        environment:
            - API_PORT=8090
        restart: unless-stopped