version: '3.8'

services:

    jni_davinci_local_bridge:
        container_name: jni_davinci_local_bridge
        image: jni_davinci_local_bridge
        ports:
            - "8090:8090"
        environment:
            - API_PORT=8090
        restart: unless-stopped